E-commerce ETL Project Notebook

In [1]:
import pandas as pd

customerDF = pd.read_csv("../Data/raw/olist_customers_dataset.csv")
orderItemDF = pd.read_csv("../Data/raw/olist_order_items_dataset.csv")
orderPaymentDF = pd.read_csv("../Data/raw/olist_order_payments_dataset.csv")
orderDf = pd.read_csv("../Data/raw/olist_orders_dataset.csv")
productsDF = pd.read_csv("../Data/raw/olist_products_dataset.csv")
sellersDF = pd.read_csv("../Data/raw/olist_sellers_dataset.csv")

### Profiling template that to follow
# Preview
df.head()

# Basic Information
df.shape
df.columns.to_list()

# Data Types
df.dtypes

# Missing Values
df.isnull().sum()

# Duplicate Rows
df.duplicated().sum()

# Candidate Key Check
# (Depends on the table)

profiling the customer dataset

In [2]:
# customerDF.head(20)
# # print(customerDF.size)
# # print(customerDF.columns)
# # print(customerDF.info())
# # print(customerDF.shape)

# # print(customerDF.isnull().sum())

# # print(customerDF.duplicated().sum())

# print("Total Rows:", customerDF.shape[0])
# print("Unique customer_id:", customerDF["customer_id"].nunique())
# print("Unique customer_unique_id:", customerDF["customer_unique_id"].nunique())

# customer_counts = customerDF["customer_unique_id"].value_counts()
# print(customer_counts)
# repeated_customers = customer_counts[customer_counts > 1]

# print("Repeated customers:", len(repeated_customers))

# customerDF[
#     customerDF["customer_unique_id"].isin(repeated_customers.index)
# ].head(20)

print("Rows:", customerDF.shape[0])
print("Columns:", customerDF.shape[1])
print("Columns name:", customerDF.columns.to_list())
print("Missing values:", customerDF.isnull().sum())
print("Duplicated Row:", customerDF.duplicated().sum())
print("primary key: customer_id")

customerDF.dtypes

Rows: 99441
Columns: 5
Columns name: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Missing values: customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Duplicated Row: 0
primary key: customer_id

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

profiling the orders dataset

In [3]:
# Basic Information
orderDf.shape
orderDf.columns.to_list()

# Data Types
orderDf.dtypes

# Missing Values
orderDf.isnull().sum()

# Duplicate Rows
orderDf.duplicated().sum()

# Candidate Primary Key
orderDf["order_id"].nunique()

# Business Understanding
orderDf["order_status"].unique()
orderDf["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

### orders observation 
- column names are fine no change needed
- data type of timestamps need to change
- missing values for col - order_approved_at, order_delivered_carrier_date, order_delivered_customer_date
- no duplicate value

profiling the orders items dataset

In [4]:
# basic info
orderItemDF.shape
orderItemDF.columns

# data type
orderItemDF.dtypes

# missing value
orderItemDF.isnull().sum()

#duplicate values
orderItemDF.duplicated().sum()

# candidate key investigation
orderItemDF["order_id"].nunique()
orderItemDF["order_item_id"].nunique()

21

### Order Items Observations

- No duplicate rows.
- No missing values.
- `order_id` is not unique because one order can contain multiple items.
- Candidate composite primary key: (`order_id`, `order_item_id`).

profiling the orders payment dataset

In [5]:
# preview
orderPaymentDF.head()

# basic info
orderPaymentDF.shape
orderPaymentDF.columns.to_list()

# datatype
orderPaymentDF.dtypes

# missing value
orderPaymentDF.isnull().sum()

# Duplicate rows
orderPaymentDF.duplicated().sum()

# candidate key investigation
orderPaymentDF["order_id"].nunique()
orderPaymentDF.shape[0]
orderPaymentDF.head(40)

#payment method value
orderPaymentDF["payment_type"].unique().tolist()

#Payment method counts
orderPaymentDF["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

### Observations

- No duplicate rows.
- No missing values.
- Multiple payment methods are available.
- Credit card is the most common payment method.
- Candidate composite primary key: (order_id, payment_sequential).

profiling the products dataset

In [6]:
# overview
productsDF.head(20)

# basic info
productsDF.shape
productsDF.columns.tolist()

# datatype
productsDF.dtypes

# missing value
productsDF.isnull().sum() 

# duplicate values
productsDF.duplicated().sum()

productsDF["product_category_name"].unique()
productsDF["product_category_name"].value_counts().to_dict()

{'cama_mesa_banho': 3029,
 'esporte_lazer': 2867,
 'moveis_decoracao': 2657,
 'beleza_saude': 2444,
 'utilidades_domesticas': 2335,
 'automotivo': 1900,
 'informatica_acessorios': 1639,
 'brinquedos': 1411,
 'relogios_presentes': 1329,
 'telefonia': 1134,
 'bebes': 919,
 'perfumaria': 868,
 'papelaria': 849,
 'fashion_bolsas_e_acessorios': 849,
 'cool_stuff': 789,
 'ferramentas_jardim': 753,
 'pet_shop': 719,
 'eletronicos': 517,
 'construcao_ferramentas_construcao': 400,
 'eletrodomesticos': 370,
 'malas_acessorios': 349,
 'consoles_games': 317,
 'moveis_escritorio': 309,
 'instrumentos_musicais': 289,
 'eletroportateis': 231,
 'casa_construcao': 225,
 'livros_interesse_geral': 216,
 'fashion_calcados': 173,
 'moveis_sala': 156,
 'climatizacao': 124,
 'livros_tecnicos': 123,
 'telefonia_fixa': 116,
 'casa_conforto': 111,
 'market_place': 104,
 'alimentos_bebidas': 104,
 'fashion_roupa_masculina': 95,
 'moveis_cozinha_area_de_servico_jantar_e_jardim': 94,
 'sinalizacao_e_seguranca': 93,
 'construcao_ferramentas_seguranca': 91,
 'eletrodomesticos_2': 90,
 'construcao_ferramentas_jardim': 88,
 'alimentos': 82,
 'bebidas': 81,
 'construcao_ferramentas_iluminacao': 78,
 'agro_industria_e_comercio': 74,
 'industria_comercio_e_negocios': 68,
 'artigos_de_natal': 65,
 'audio': 58,
 'artes': 55,
 'fashion_underwear_e_moda_praia': 53,
 'dvds_blu_ray': 48,
 'moveis_quarto': 45,
 'construcao_ferramentas_ferramentas': 39,
 'portateis_casa_forno_e_cafe': 31,
 'livros_importados': 31,
 'pcs': 30,
 'cine_foto': 28,
 'fashion_roupa_feminina': 27,
 'musica': 27,
 'artigos_de_festas': 26,
 'fashion_esporte': 19,
 'artes_e_artesanato': 19,
 'flores': 14,
 'fraldas_higiene': 12,
 'la_cuisine': 10,
 'portateis_cozinha_e_preparadores_de_alimentos': 10,
 'moveis_colchao_e_estofado': 10,
 'tablets_impressao_imagem': 9,
 'fashion_roupa_infanto_juvenil': 5,
 'casa_conforto_2': 5,
 'pc_gamer': 3,
 'seguros_e_servicos': 2,
 'cds_dvds_musicais': 1}

### observation 
- few column names are having spelling mistake ("
")
- data type is fine
- multiple missing values in all columns except product_id
- no duplicate values
- product_id is primary key

profiling the sellers dataset

In [7]:
# overview
sellersDF.head()

# basic info
sellersDF.shape
sellersDF.columns.tolist()

# data type
sellersDF.dtypes

# missing value
sellersDF.isnull().sum()

# duplicate value
sellersDF.duplicated().sum()

0

### observations

- `seller_id` is the primary key
- no missing value
- no duplicate value

Cleaning phase

### Cleaning Summary - Customers

- No missing values found.
- No duplicate rows found.
- Data types are appropriate.
- No invalid records identified.
- No cleaning required.

orders DF cleaning

In [8]:
orderDf.head()

orderDf[orderDf["order_approved_at"].isnull()][
    ["order_id", "order_status", "order_purchase_timestamp", "order_approved_at"]
]

orderDf[orderDf["order_approved_at"].isnull()]["order_status"].value_counts()


orderDf[orderDf["order_delivered_carrier_date"].isnull()][
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_carrier_date",
    ]
]

orderDf[orderDf["order_delivered_carrier_date"].isnull()]["order_status"].value_counts()



orderDf[orderDf["order_delivered_customer_date"].isnull()][
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
    ]
]

orderDf[orderDf["order_delivered_customer_date"].isnull()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

### cleaning of orders

- coverting the data type of object to datetime

In [9]:
date_col = ["order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"]

for col in date_col:
   orderDf[col] =  pd.to_datetime(orderDf[col])

orderDf.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

### Orders Cleaning Complete

- Timestamp columns converted from object to datetime.
- Row count unchanged.
- Missing timestamp values retained as they represent valid business scenarios.
- No duplicate rows removed.

### products cleaning
- rectifying misspelled column names i.e. product_name_lenght", "product_description_lenght", "product_weight_g

In [10]:
productsDF.rename(columns=
                  {"product_name_lenght":"product_name_length", 
                   "product_description_lenght":"product_description_length" }, inplace=True)

productsDF.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

### order item cleaing

In [11]:
orderItemDF.columns.to_list()
orderItemDF.dtypes

orderItemDF["shipping_limit_date"] = pd.to_datetime(orderItemDF["shipping_limit_date"])

orderItemDF.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

### cleaning payments
- nothing to clean

In [12]:
orderPaymentDF.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

### cleaning seller
- nothing to clean

### Transformation Phase

# orders

In [13]:
orderDf.head()

# calculating the days it took to deliver the order
orderDf["delivery_days"] = (orderDf["order_delivered_customer_date"]- orderDf["order_purchase_timestamp"]).dt.days

orderDf[
    [
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "delivery_days"
    ]
].head(10)

# finding the year in which order was placed
orderDf["order_year"] = orderDf["order_purchase_timestamp"].dt.year

# finding out the month in which order was placed
orderDf["order_month"] = orderDf["order_purchase_timestamp"].dt.month

# finding out the weekday in which order was placed
orderDf["order_weekday"] = orderDf["order_purchase_timestamp"].dt.day_name()

# How many days earlier or later was the order delivered compared with the estimated delivery date?

orderDf["delivery_vs_estimated_days"] = (
    orderDf["order_delivered_customer_date"]
    - orderDf["order_estimated_delivery_date"]
).dt.days

orderDf[
    [
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_vs_estimated_days"
    ]
].head(10)


# How long did it take for an order to get approved after it was purchased?
orderDf["approval_time_hours"] = (orderDf["order_approved_at"] - orderDf["order_purchase_timestamp"]).dt.total_seconds()/3600

orderDf[
    [
        "order_approved_at",
        "order_purchase_timestamp",
        "approval_time_hours"
    ]
].head(10)


orderDf[
    [
        "order_id",
        "delivery_days",
        "order_year",
        "order_month",
        "order_weekday",
        "delivery_vs_estimated_days",
        "approval_time_hours"
    ]
].head(10)

,order_id,delivery_days,order_year,order_month,order_weekday,delivery_vs_estimated_days,approval_time_hours
0,e481f51cbdc54678b7cc49136f2d6af7,8.0,2017,10,Monday,-8.0,0.178333
1,53cdb2fc8bc7dce0b6741e2150273451,13.0,2018,7,Tuesday,-6.0,30.713889
2,47770eb9100c2d0c44946d9cf07ec65d,9.0,2018,8,Wednesday,-18.0,0.276111
3,949d5b44dbf5de918fe9c16f97b45f8a,13.0,2017,11,Saturday,-13.0,0.298056
4,ad21c59c0840e6cb83a9ceb5573f8159,2.0,2018,2,Tuesday,-10.0,1.030556
5,a4591c265e18cb1dcee52889e2d8acc3,16.0,2017,7,Sunday,-6.0,0.218889
6,136cce7faa42fdb2cefd53fdc79a6098,NaN,2017,4,Tuesday,NaN,49.052500
7,6514b8ad8028c9f2cc2374ded245783f,9.0,2017,5,Tuesday,-12.0,0.194722
8,76c6e866289321a7c93b82b54852dc33,9.0,2017,1,Monday,-32.0,32.360556
9,e69bfb5eb88e0ed6a785585b27e16dbf,18.0,2017,7,Saturday,-7.0,0.175000

### transforming order items

In [14]:
orderItemDF

#We want to know the total value of each order item, including freight. so the logic is price* freight value

orderItemDF['total_item_value'] = orderItemDF["price"] + orderItemDF["freight_value"]

orderItemDF[
    [
        "order_id",
        "price",
        "freight_value",
        "total_item_value"
    ]
].head(10)

                           order_id   price  freight_value  total_item_value
0  00010242fe8c5a6d1ba2dd792cb16214   58.90          13.29             72.19
1  00018f77f2f0320c557190d7a144bdd3  239.90          19.93            259.83
2  000229ec398224ef6ca0657da4fc703e  199.00          17.87            216.87
3  00024acbcdf0a6daa1e931b038114c75   12.99          12.79             25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9  199.90          18.14            218.04
5  00048cc3ae777c65dbb7d2a0634bc1ea   21.90          12.69             34.59
6  00054e8431b9d7675808bcb819fb4a32   19.90          11.85             31.75
7  000576fe39319847cbb9d288c5617fa6  810.00          70.75            880.75
8  0005a1a1728c9d785b8e2b08b904576c  145.95          11.65            157.60
9  0005f50442cb953dcd1d21e1fb923495   53.99          11.40             65.39

### Phase 4 — Data Integration

In [15]:
# merging the customer and orders DF

orderCustomerDf = pd.merge(
    orderDf, customerDF, how="left", on="customer_id"
)

orderCustomerDf
print("Orders before:", orderDf.shape[0])
print("After merge:", orderCustomerDf.shape[0])
orderCustomerDf.columns.tolist()

Orders before: 99441
After merge: 99441

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'delivery_days',
 'order_year',
 'order_month',
 'order_weekday',
 'delivery_vs_estimated_days',
 'approval_time_hours',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [16]:
# merging orders and order items

orderItemsCustomerDf = pd.merge(
    orderCustomerDf,
    orderItemDF,
    how="left",
    on="order_id"
)

orderItemsCustomerDf.shape

(113425, 25)

In [17]:
# merging product DF 

orderProductDf = pd.merge(
    orderItemsCustomerDf,
    productsDF,
    how="left",
    on="product_id"
)

orderProductDf.shape
orderProductDf.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,order_year,...,freight_value,total_item_value,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,2017,...,8.72,38.71,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,2018,...,22.76,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,2018,...,19.22,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,2017,...,27.20,72.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,2018,...,8.72,28.62,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

In [18]:
# merging seller DF

masterDf = pd.merge(
    orderProductDf,
    sellersDF,
    how="left",
    on="seller_id"
)

masterDf.shape
masterDf.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,order_year,...,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,2017,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,2018,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,2018,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,2017,...,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842.0,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,2018,...,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752.0,mogi das cruzes,SP

## creating payment summary DF 
- since the payment DF has multiple payments per order we will have to merge all of the payment of single order.

In [25]:
# merging the orders 
paymentSummaryDF = orderPaymentDF.groupby("order_id")["payment_value"].sum()

# converting the series into DF 
paymentSummaryDF = paymentSummaryDF.reset_index()


# changing the column name 
paymentSummaryDF = paymentSummaryDF.rename(
    columns={"payment_value": "total_payment_value"}
)

paymentSummaryDF
paymentSummaryDF.head()
paymentSummaryDF.shape

(99440, 2)